export enum ROLES {
  ADMIN = "ADMIN",
  SUPERADMIN = "SUPERADMIN",
  DAERAH = "DAERAH",
  SUBDAERAH = "SUBDAERAH",
  DESA = "DESA",
  SUBDESA ="SUBDESA" ,
  KELOMPOK = "KELOMPOK",
  SUBKELOMPOK = "SUBKELOMPOK",
}
